import Link from "next/link";
import { getSession } from "@/lib/session";
import { Navbar } from "@/components/navbar";

export default async function AboutPage() {
  const session = await getSession();
  const isLoggedIn = Boolean(session);

  return (
    <div className="min-h-screen">
      <Navbar activePath="/about" />

      <main className="mx-auto max-w-4xl px-5 py-16 sm:px-8">
        <div className="mb-12 text-center">
          <h1 className="text-4xl font-bold tracking-tight">About AI Study Buddy</h1>
          <p className="mt-4 text-xl text-muted">A focused academic companion built for students who want to understand, not just memorize.</p>
        </div>

        <div className="prose prose-slate max-w-none space-y-12">
          <section className="rounded-2xl border border-border bg-white p-8 shadow-sm">
            <h2 className="text-2xl font-bold mb-4">Our mission</h2>
            <p className="text-muted leading-7">
              AI Study Buddy exists to make expert-quality tutoring accessible to every student, regardless of their school, location, or financial situation. We believe that understanding a concept deeply is more valuable than having an answer handed to you — which is why our three tutoring modes are designed around active learning.
            </p>
            <p className="text-muted leading-7 mt-4">
              Every feature we build starts with the same question: &ldquo;Does this help students learn better?&rdquo; Not &ldquo;Does this look impressive?&rdquo;
            </p>
          </section>

          <section className="rounded-2xl border border-border bg-white p-8 shadow-sm">
            <h2 className="text-2xl font-bold mb-4">How it works</h2>
            <p className="text-muted leading-7">
              Students create a private account, start a study session in their subject of choice, and interact with an AI tutor that adapts to their chosen mode. Conversations are saved privately and can be resumed at any time.
            </p>
            <p className="text-muted leading-7 mt-4">
              The platform is powered by either OpenAI&rsquo;s GPT models or Ollama, an open-source, locally-hosted AI runtime. All tutor instructions, API keys, and personal data are kept server-side and never exposed to the browser.
            </p>
          </section>

          <section className="rounded-2xl border border-border bg-white p-8 shadow-sm">
            <h2 className="text-2xl font-bold mb-4">Privacy & safety</h2>
            <p className="text-muted leading-7">
              Your study sessions are completely private. No instructor, administrator, or other student can read your conversations. We apply content moderation to keep the platform safe and age-appropriate.
            </p>
            <p className="text-muted leading-7 mt-4">
              AI responses are generated by a language model and can occasionally be incorrect. We always encourage students to verify important academic work with authoritative sources such as textbooks and teachers.
            </p>
          </section>

          <section className="rounded-2xl border border-border bg-white p-8 shadow-sm">
            <h2 className="text-2xl font-bold mb-4">Built with care</h2>
            <div className="grid gap-4 sm:grid-cols-2 mt-2">
              {[
                ["Next.js", "App Router with TypeScript for a fast, type-safe experience."],
                ["Better Auth", "Secure authentication with email/password and Google OAuth."],
                ["MongoDB", "Private, indexed conversation storage with no shared data."],
                ["OpenAI / Ollama", "Dual AI provider support for flexibility and privacy."],
                ["TanStack Query", "Efficient client-side data fetching with automatic caching."],
                ["Tailwind CSS", "Responsive, consistent design without bloat."],
              ].map(([tech, desc]) => (
                <div key={tech} className="flex gap-3">
                  <span className="mt-0.5 text-primary font-bold">✓</span>
                  <div>
                    <p className="font-semibold">{tech}</p>
                    <p className="text-sm text-muted">{desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>
        </div>

        <div className="mt-12 text-center">
          <Link
            href={isLoggedIn ? "/dashboard" : "/login?mode=register"}
            className="inline-block rounded-xl bg-primary px-8 py-4 font-bold text-white hover:bg-primary-dark shadow-lg shadow-blue-200"
          >
            {isLoggedIn ? "Go to dashboard" : "Start studying free"}
          </Link>
        </div>
      </main>
    </div>
  );
}
